repos:
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: v0.4.0
    hooks:
      - id: sync-with-uv
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.1
    hooks:
      - id: ruff-format
      - id: ruff-check
  # - repo: https://github.com/charliermarsh/ruff-pre-commit
  #   rev: "v0.13.1"
  #   hooks:
  #     - id: ruff
  #       args: [--fix, --exit-non-zero-on-fix]
  #       exclude: ^(.*/)?(\.venv|_build|build|dist|node_modules|configs|examples|\.next|\.git|\.mypy_cache|\.pytest_cache|\.tox|\.eggs|\.cache|\.hypothesis|\.mypy|\.nox|\.pre-commit|\.vscode|\.github|\.idea|__pycache__)/
  # - repo: https://github.com/psf/black
  #   rev: 25.9.0
  #   hooks:
  #     - id: black
  #       language_version: python3.11
  #       exclude: ^(.*/)?(\.venv|_build|build|dist|node_modules|configs|examples|\.next|\.git|\.mypy_cache|\.pytest_cache|\.tox|\.eggs|\.cache|\.hypothesis|\.mypy|\.nox|\.pre-commit|\.vscode|\.github|\.idea|__pycache__)/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        additional_dependencies:
        - 'pydantic[mypy]>=2.11.9'
        args: [
          "--install-types",
          "--non-interactive",
          "--ignore-missing-imports",
          "--python-version=3.13",
        ]
        exclude: ^(.*/)?(alembic|\.venv|_build|build|dist|node_modules|configs|examples|\.next|\.git|\.mypy_cache|\.pytest_cache|\.tox|\.eggs|\.cache|\.hypothesis|\.mypy|\.nox|\.pre-commit|\.vscode|\.github|\.idea|__pycache__)/