version: '3.5'

services:
  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=strategy_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=strategy_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    container_name: postgres
    ports:
      - "5432:5432"

  ### Redis ################################################
  redis:
    image: redis:6-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com       # Set the pgAdmin default admin email
      PGADMIN_DEFAULT_PASSWORD: admin_password       # Set the pgAdmin default admin password
    ports:
      - "8080:80"  # Expose pgAdmin on port 8080
    depends_on:
      - postgres    # Ensure PostgreSQL starts before pgAdmin
    container_name: pgadmin

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"

volumes:
  postgres-data: