"""timeframe is string field

Revision ID: 1f1593afc15a
Revises: 20256b7cf1a0
Create Date: 2024-09-18 22:36:06.277957

"""


# revision identifiers, used by Alembic.
revision = "1f1593afc15a"
down_revision = "20256b7cf1a0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
