"""initial revision

Revision ID: 20256b7cf1a0
Revises: 
Create Date: 2024-09-18 22:35:22.380960

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "20256b7cf1a0"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("timeframe", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_candles_exchange"), "candles", ["exchange"], unique=False)
    op.create_index(op.f("ix_candles_symbol"), "candles", ["symbol"], unique=False)
    op.create_index(op.f("ix_candles_timeframe"), "candles", ["timeframe"], unique=False)
    op.create_index(op.f("ix_candles_timestamp"), "candles", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_timestamp"), table_name="candles")
    op.drop_index(op.f("ix_candles_timeframe"), table_name="candles")
    op.drop_index(op.f("ix_candles_symbol"), table_name="candles")
    op.drop_index(op.f("ix_candles_exchange"), table_name="candles")
    op.drop_table("candles")
    # ### end Alembic commands ###
