"""drop time column

Revision ID: 2b02ec57400d
Revises: a914705a8001
Create Date: 2024-09-20 22:15:12.249758

"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "2b02ec57400d"
down_revision = "a914705a8001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candles_time", table_name="candles")
    op.drop_column("candles", "time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candles",
        sa.Column(
            "time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index("ix_candles_time", "candles", ["time"], unique=False)
    # ### end Alembic commands ###
