"""timeframe is string field

Revision ID: 79973f2443b4
Revises: 1f1593afc15a
Create Date: 2024-09-18 22:36:36.184135

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "79973f2443b4"
down_revision = "1f1593afc15a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_candles_timeframe", table_name="candles")
    op.drop_column("candles", "timeframe")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candles", sa.Column("timeframe", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True)
    )
    op.create_index("ix_candles_timeframe", "candles", ["timeframe"], unique=False)
    # ### end Alembic commands ###
