"""Initial migration

Revision ID: 8ff2b4be1dab
Revises:
Create Date: 2024-09-19 16:05:56.905920

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ff2b4be1dab"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=True),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("exchange", sa.String(), nullable=True),
        sa.Column("symbol", sa.String(), nullable=True),
        sa.Column("timeframe", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("exchange", "symbol", "timeframe", "timestamp", name="unique_candle_constraint"),
    )
    op.create_index(op.f("ix_candles_exchange"), "candles", ["exchange"], unique=False)
    op.create_index(op.f("ix_candles_symbol"), "candles", ["symbol"], unique=False)
    op.create_index(op.f("ix_candles_timeframe"), "candles", ["timeframe"], unique=False)
    op.create_index(op.f("ix_candles_timestamp"), "candles", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_timestamp"), table_name="candles")
    op.drop_index(op.f("ix_candles_timeframe"), table_name="candles")
    op.drop_index(op.f("ix_candles_symbol"), table_name="candles")
    op.drop_index(op.f("ix_candles_exchange"), table_name="candles")
    op.drop_table("candles")
    # ### end Alembic commands ###
