"""timeframe is string field

Revision ID: a87246901536
Revises: 79973f2443b4
Create Date: 2024-09-18 22:36:46.405375

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a87246901536"
down_revision = "79973f2443b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candles", sa.Column("timeframe", sa.String(), nullable=True))
    op.create_index(op.f("ix_candles_timeframe"), "candles", ["timeframe"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_timeframe"), table_name="candles")
    op.drop_column("candles", "timeframe")
    # ### end Alembic commands ###
