"""set values in time column

Revision ID: a914705a8001
Revises: ae740b8fd8f1
Create Date: 2024-09-20 22:10:54.292906

"""

from __future__ import annotations

from alembic import op

# revision identifiers, used by Alembic.
revision = "a914705a8001"
down_revision = "ae740b8fd8f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        UPDATE candles
        SET time = to_timestamp(timestamp / 1000) AT TIME ZONE 'UTC'
    """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
