"""rename timestamp_tz to time

Revision ID: ae740b8fd8f1
Revises: e68eb978b5fc
Create Date: 2024-09-20 22:08:51.459860

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "ae740b8fd8f1"
down_revision = "e68eb978b5fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("candles", sa.Column("time", sa.TIMESTAMP(timezone=True), nullable=True))
    op.drop_index("ix_candles_timestamp_tz", table_name="candles")
    op.create_index(op.f("ix_candles_time"), "candles", ["time"], unique=False)
    op.drop_column("candles", "timestamp_tz")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candles", sa.Column("timestamp_tz", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_candles_time"), table_name="candles")
    op.create_index("ix_candles_timestamp_tz", "candles", ["timestamp_tz"], unique=False)
    op.drop_column("candles", "time")
    # ### end Alembic commands ###
