"""Add backtest models

Revision ID: c26039d3a3d8
Revises: 2b02ec57400d
Create Date: 2024-12-24 19:53:22.382784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c26039d3a3d8"
down_revision = "2b02ec57400d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backtest_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("strategy_name", sa.String(), nullable=False),
        sa.Column("start_balance", sa.Float(), nullable=False),
        sa.Column("end_balance", sa.Float(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_backtest_results_id"), "backtest_results", ["id"], unique=False)
    op.create_table(
        "baseline_curve",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_result_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["backtest_result_id"], ["backtest_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_baseline_curve_id"), "baseline_curve", ["id"], unique=False)
    op.create_table(
        "equity_curve",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_result_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["backtest_result_id"], ["backtest_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_equity_curve_id"), "equity_curve", ["id"], unique=False)
    op.create_table(
        "performance_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_result_id", sa.Integer(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("win_rate", sa.Float(), nullable=False),
        sa.Column("sharpe_ratio", sa.Float(), nullable=True),
        sa.Column("mdart_sharpe", sa.Float(), nullable=True),
        sa.Column("calmar_ratio", sa.Float(), nullable=True),
        sa.Column("omega_ratio", sa.Float(), nullable=True),
        sa.Column("serenity_index", sa.Float(), nullable=True),
        sa.Column("average_win_loss", sa.Float(), nullable=True),
        sa.Column("average_win", sa.Float(), nullable=True),
        sa.Column("average_loss", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["backtest_result_id"], ["backtest_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_performance_metrics_id"), "performance_metrics", ["id"], unique=False)
    op.create_table(
        "risk_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_result_id", sa.Integer(), nullable=False),
        sa.Column("total_losing_streak", sa.Integer(), nullable=False),
        sa.Column("largest_losing_trade", sa.Float(), nullable=False),
        sa.Column("largest_winning_trade", sa.Float(), nullable=False),
        sa.Column("total_winning_streak", sa.Integer(), nullable=False),
        sa.Column("current_streak", sa.Integer(), nullable=False),
        sa.Column("expectancy", sa.Float(), nullable=False),
        sa.Column("expected_net_profit", sa.Float(), nullable=False),
        sa.Column("average_holding_period", sa.Float(), nullable=False),
        sa.Column("gross_profit", sa.Float(), nullable=False),
        sa.Column("gross_loss", sa.Float(), nullable=False),
        sa.Column("max_drawdown", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["backtest_result_id"], ["backtest_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_risk_metrics_id"), "risk_metrics", ["id"], unique=False)
    op.create_table(
        "trade_metrics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("backtest_result_id", sa.Integer(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("total_winning_trades", sa.Integer(), nullable=False),
        sa.Column("total_losing_trades", sa.Integer(), nullable=False),
        sa.Column("starting_balance", sa.Float(), nullable=False),
        sa.Column("finishing_balance", sa.Float(), nullable=False),
        sa.Column("longs_count", sa.Integer(), nullable=False),
        sa.Column("longs_percentage", sa.Float(), nullable=False),
        sa.Column("shorts_count", sa.Integer(), nullable=False),
        sa.Column("shorts_percentage", sa.Float(), nullable=False),
        sa.Column("fee", sa.Float(), nullable=False),
        sa.Column("total_open_trades", sa.Integer(), nullable=False),
        sa.Column("open_pl", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["backtest_result_id"], ["backtest_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trade_metrics_id"), "trade_metrics", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_metrics_id"), table_name="trade_metrics")
    op.drop_table("trade_metrics")
    op.drop_index(op.f("ix_risk_metrics_id"), table_name="risk_metrics")
    op.drop_table("risk_metrics")
    op.drop_index(op.f("ix_performance_metrics_id"), table_name="performance_metrics")
    op.drop_table("performance_metrics")
    op.drop_index(op.f("ix_equity_curve_id"), table_name="equity_curve")
    op.drop_table("equity_curve")
    op.drop_index(op.f("ix_baseline_curve_id"), table_name="baseline_curve")
    op.drop_table("baseline_curve")
    op.drop_index(op.f("ix_backtest_results_id"), table_name="backtest_results")
    op.drop_table("backtest_results")
    # ### end Alembic commands ###
