"""Add timestamp_tz column to candles

Revision ID: e68eb978b5fc
Revises: 8ff2b4be1dab
Create Date: 2024-09-20 22:01:08.895076

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e68eb978b5fc"
down_revision = "8ff2b4be1dab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candles",
        sa.Column("timestamp_tz", sa.TIMESTAMP(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_candles_timestamp_tz"),
        "candles",
        ["timestamp_tz"],
        unique=False,
    )
    op.execute(
        """
        UPDATE candles
        SET timestamp_tz = to_timestamp(timestamp / 1000) AT TIME ZONE 'UTC'
    """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_candles_timestamp_tz"), table_name="candles")
    op.drop_column("candles", "timestamp_tz")
    # ### end Alembic commands ###
